# Generated by Django 4.1.3 on 2023-04-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtraImages',
            new_name='ExtraImage',
        ),
        migrations.AlterModelOptions(
            name='extraimage',
            options={'verbose_name': 'Imagen extra de producto', 'verbose_name_plural': 'Imagenes extra de producto'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
